# Generated by Django 3.1 on 2020-08-16 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='f',
            field=models.FileField(default=None, upload_to='files/'),
        ),
    ]
