# Generated by Django 3.1 on 2020-08-16 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_file_f'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='f',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='file',
            name='path',
        ),
    ]
