# Generated by Django 3.1 on 2020-08-16 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200816_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(default=None, max_length=200, upload_to='files/'),
        ),
    ]
